depapiVersion: apps/v1
kind: Deployment
metadata:
  name: joetechdep
spec:
  selector:
    matchLabels:
      app: joe
  template:
    metadata:
      labels:
        app: joe
    spec:
      containers:
      - name: joetech
        image: jeaggrey/webapp:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: joeappserv
spec:
  type: NodePort
  selector:
    app: joe
  ports:
  - port: 80
    targetPort: 8080 
 
